CREATE TABLE IF NOT EXISTS posts (
	id	SERIAL PRIMARY KEY,
	user_id INT NOT NULL,
	title	VARCHAR (255) NOT NULL,
	body	VARCHAR NOT NULL,

	/*timestamp*/
	created_at	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
